version: "3.3"

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=felipe
      - POSTGRES_PASSWORD=123456
    ports:
      - 5433:5432
    volumes:
      - "~/postgres_data:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pruebas@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - 5051:80
