version: "3.3"

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=felipe
      - POSTGRES_PASSWORD=123456
    ports:
      - 5433:5432
    volumes:
      - "~/postgres_data:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pruebas@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - 5051:80

  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=my_store
      - MYSQL_USER=felipe
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - "~/mysql_data:/var/lib/mysql"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - PMA_HOST=mysql
    ports:
      - 8080:80
